# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.7.0"
"rocks-git.nvim" = "1.2.1"
"rocks-config.nvim" = { git = "nvim-neorocks/rocks-config.nvim" }

# Everyday tools
vim-obsession = { git = "tpope/vim-obsession" }
vim-abolish = { git = "tpope/vim-abolish" }
vim-fugitive = { git = "tpope/vim-fugitive" }
vim-matchup = { git = "andymass/vim-matchup" }
vim-easy-align = { git = "junegunn/vim-easy-align" }
nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter" }
"mini.comment" = { git = "echasnovski/mini.comment" }
"which-key.nvim" = { git = "folke/which-key.nvim", config = true }

# UI stuff
"nightfox.nvim" = { git = "EdenEast/nightfox.nvim" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim", config = true }
nvim-web-devicons = "0.99"
"dressing.nvim" = { git = "stevearc/dressing.nvim", config = true }
"mini.statusline" = { git = "echasnovski/mini.statusline" }
"mini.tabline" = { git = "echasnovski/mini.tabline" }
"nvim-notify" = { git = "rcarriga/nvim-notify" }
"indent-blankline.nvim" = { git = "lukas-reineke/indent-blankline.nvim" }

# Fuzzy finder
"telescope.nvim" = "scm-1"

# LSP and tools stuff
nvim-lspconfig = { git = "neovim/nvim-lspconfig" }
"neoconf.nvim" = { git = "folke/neoconf.nvim" }
"neodev.nvim" = { git = "folke/neodev.nvim" }
lspkind-nvim = { git = "onsails/lspkind-nvim" }
"mason.nvim" = { git = "williamboman/mason.nvim" }
"mason-lspconfig.nvim" = { git = "williamboman/mason-lspconfig.nvim" }

# Coding helpers
nvim-cmp = { git = "hrsh7th/nvim-cmp" }
cmp-buffer = { git = "hrsh7th/cmp-buffer" }
cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp" }
cmp-nvim-lua = { git = "hrsh7th/cmp-nvim-lua" }
cmp-omni = { git = "hrsh7th/cmp-omni" }
cmp-path = { git = "hrsh7th/cmp-path" }
cmp-treesitter = { git = "ray-x/cmp-treesitter" }
cmp-latex-symbols = { git = "kdheepak/cmp-latex-symbols" }
cmp-pandoc-references = { git = "jmbuhr/cmp-pandoc-references" }

luasnip = "2.2.0"
friendly-snippets = { git = "rafamadriz/friendly-snippets" }
# "formatter.nvim" = { git = "mhartington/formatter.nvim" }
# nvim-lint = { git = "mfussenegger/nvim-lint" }
rustaceanvim = "3.17.2"
"ltex-ls.nvim" = { git = "vigoux/ltex-ls.nvim" }
"none-ls.nvim" = { git = "nvimtools/none-ls.nvim" }

quarto-nvim = { git = "quarto-dev/quarto-nvim" }
"otter.nvim" = { git = "jmbuhr/otter.nvim" }
vim-markdown = { git = "preservim/vim-markdown" }
vimtex = { git = "lervag/vimtex" }
"image.nvim" = "scm-1"
molten-nvim = { git = "benlubas/molten-nvim" }

# Other random things
vim-startuptime = { git = "dstein64/vim-startuptime" }
"plenary.nvim" = "scm"
