require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "bash",
    "c",
    "cpp",
    "html",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "regex",
    "rust",
    "vim",
    "vimdoc",
    "zig",
  },
  highlight = { enable = true },
  indent = { enable = true },
  matchup = { enable = true },
}
